{{- if and (.Values.useAWSJDBCWrapper) (not .Values.customImage) }}
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        # name: quay.io/keycloak/keycloak:nightly
        # Workaround custom image for https://github.com/keycloak/keycloak/issues/28949
        name: quay.io/aschwart/keycloak:local
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
{{ end }}
