{{ if .Values.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak-metrics
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: keycloak
  podMetricsEndpoints:
    - port: management
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
---
{{ if .Values.otel }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak-otel
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: keycloak
  podMetricsEndpoints:
    - port: otel-prometheus
{{ end }}
{{ end }}
