name: Setup Go Task
description: Installs Go Task

runs:
  using: composite
  steps:
    - name: Install Task
      uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
