name: ROSA Daily Scheduled Run

on:
  schedule:
    - cron: '0 5 * * 1-5' # Runs At 05:00 UTC on every day-of-week from Monday through Friday.
  workflow_dispatch:

# env:
#   CLUSTER_PREFIX: gh-keycloak

jobs:
  keycloak-deploy-active-active:
    name: ROSA Scheduled Create Active/Active cluster with External Infinispan and Persistent Sessions
    if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-benchmark'
    uses: ./.github/workflows/rosa-multi-az-cluster-create.yml
    with:
      clusterPrefix: gh-keycloak # ${{ env.CLUSTER_PREFIX }} -- unfortunately 'env.' doesn't work here
      enableMultiSiteFeature: true
      enableExternalInfinispanFeature: false
      activeActive: true
    secrets: inherit

  run-functional-tests-active-active:
    needs: keycloak-deploy-active-active
    uses: ./.github/workflows/rosa-run-crossdc-func-tests.yml
    with:
      activeActive: true
      clusterPrefix: gh-keycloak # ${{ env.CLUSTER_PREFIX }} -- unfortunately 'env.' doesn't work here
      skipEmbeddedCaches: true
      skipRemoteCaches: true
    secrets: inherit

  run-scaling-benchmark-active-active:
    needs: run-functional-tests-active-active
    uses: ./.github/workflows/rosa-scaling-benchmark.yml
    with:
      clusterName: gh-keycloak-a # ${{ env.CLUSTER_PREFIX }}-a -- unfortunately 'env.' doesn't work here
      outputArchiveSuffix: 'active-active'
    secrets: inherit
